### ISSUE TITLE
Job DEFAULT.SolrShardingMetricsJob threw an exception

### ISSUE THREAD

**Issue by hvancamp** [xenit-eu/alfred-telemetry#36]
`2020-11-04 10:59:54,098  ERROR [quartz.core.ErrorLogger] [DefaultScheduler_Worker-4] Job (DEFAULT.SolrShardingMetricsJob threw an exception.
 org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.util.NoSuchElementException: No value present]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetricsContainer.getShardState(SolrShardingMetricsContainer.java:56)
        at eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetrics.lambda$updateMetrics$2(SolrShardingMetrics.java:53)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetrics.lambda$updateMetrics$3(SolrShardingMetrics.java:51)
        at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
        at eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetrics.lambda$updateMetrics$4(SolrShardingMetrics.java:44)
        at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
        at eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetrics.updateMetrics(SolrShardingMetrics.java:38)
        at eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetricsScheduledJob.lambda$executeInternal$0(SolrShardingMetricsScheduledJob.java:27)
        at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:602)
        at eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetricsScheduledJob.executeInternal(SolrShardingMetricsScheduledJob.java:26)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
`

**Comment by tgeens** [comment]
Looks like it tries to find the `ShardSate` for a given `ShardInstance`, but cant find any match:

```
public ShardState getShardState(ShardInstance shardInstance) {
        Shard shard = shardInstance.getShard();
        return rawData.get(shard.getFloc()).get(shard).stream()
                .filter(shardState -> shardState.getShardInstance() == shardInstance).findAny().get();
    }
```

**Comment by thijslemmens** [comment]
> Looks like it tries to find the `ShardSate` for a given `ShardInstance`, but cant find any match:
> 
> ```
> public ShardState getShardState(ShardInstance shardInstance) {
>         Shard shard = shardInstance.getShard();
>         return rawData.get(shard.getFloc()).get(shard).stream()
>                 .filter(shardState -> shardState.getShardInstance() == shardInstance).findAny().get();
>     }
> ```

I didn't really know what this would do in a running system. We should fix this.

**Comment by tgeens** [comment]
Question is how ? You want to update the metrics, you loop over the shard-instances, but a shard-instance does not have any state ?

Should we report `-1` for all the shard-metrics ?

**Comment by TomVerschuerenXenit** [comment]
@thijslemmens Is wat Toon zegt een goed idee? Zoja, dan implementeer ik het.

**Comment by thijslemmens** [comment]
I think it could be a valid solution. I struggled with the cleaning up of metrics. I think, if you delete your reference for a metric, it gets garbage collected and stops showing up. However, it cannot come back anymore then. -1 could be a workaround. I suggest you go with that, and experience how that works out for Ethias.
